name: Preprocessing Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn mlflow
      - name: Verify MLproject file
        run: |
          ls -la Eksperimen_SML_Sidqi/  # Tampilkan isi direktori untuk debugging
          if [ -f "Eksperimen_SML_Sidqi/MLproject" ]; then
            echo "MLproject file found!"
            cat Eksperimen_SML_Sidqi/MLproject  # Tampilkan isi file untuk debugging
          else
            echo "MLproject file not found in Eksperimen_SML_Sidqi!"
            exit 1
          fi
      - name: Run MLflow project
        run: |
          mlflow run Eksperimen_SML_Sidqi --env-manager=local
      - name: Commit processed data
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Eksperimen_SML_Sidqi/dataset/processed/iris_processed.csv
          git commit -m "Update processed dataset" || echo "No changes to commit"

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Sidqiamn/submisi-sistem-ML2.git
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
